#!/bin/sh
cd ..
dotnet publish --self-contained -r linux-x64
cd debian
cp -r '../bin/Debug/netcoreapp3.1/linux-x64/publish' './imahex/usr/lib/imahex'
dpkg-deb --build imahex
rm -r './imahex/usr/lib/imahex'
